name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION=${TAG_NAME#v}

          if [[ "$VERSION" == *-* ]]; then
            echo "Prerelease version detected: $VERSION"
            echo "Publishing with tag 'next'..."
            npm publish --tag next
          else
            echo "Release version detected: $VERSION"
            echo "Publishing with default tag 'latest'..."
            npm publish
          fi
      - name: Publish to JSR
        run: npx jsr publish
