name: Run test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.2.0
      - name: Run Biome checks
        run: biome ci --reporter=github
        
      - name: Run tests
        env:
          YUNDICT_API_TOKEN: ${{ secrets.YUNDICT_API_TOKEN }}
          YUNDICT_API_ENDPOINT: ${{ secrets.YUNDICT_API_ENDPOINT }}
        run: bun test
